name: ui_components
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 1.1.1+1
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.2.0
  flutter_gen_runner: 4.3.0

flutter:
  assets:
    - assets/icons/
  uses-material-design: true
  generate: true

flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    package_parameter_enabled: true